import type { Metadata } from "next";
// 配置字体
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/header";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  admin,
  normal,
}: {
  children: React.ReactNode;
  admin: React.ReactNode;
  normal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <Header />
          <div className="flex">
            {admin}
            {normal}
          </div>
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
